Virtual Embedded Enviorment: include/arduino.h File Reference
include/arduino.h File Reference
The main interface to the emulation system.
#include <stdint.h>
#include <stdlib.h>
#include <avr/config.h>
#include <string>
#include "binary.h"
#include "ardulator.h"
Data Structures
class Print
Printing utilities, requires the implementation of the Print::write function to work.
class HardwareSerial
Hardware Serial represents the a basic hardware RS-232 Serial port.
Defines
#define HIGH 0x1
#define LOW 0x0
#define INPUT 0x0
#define OUTPUT 0x1
#define true 0x1
#define false 0x0
#define PI 3.1415926535897932384626433832795
#define HALF_PI 1.5707963267948966192313216916398
#define TWO_PI 6.283185307179586476925286766559
#define DEG_TO_RAD 0.017453292519943295769236907684886
#define RAD_TO_DEG 57.295779513082320876798154814105
#define SERIAL 0x0
#define DISPLAY 0x1
#define LSBFIRST 0
#define MSBFIRST 1
#define CHANGE 1
#define FALLING 2
#define RISING 3
#define INTERNAL 3
#define DEFAULT 1
#define EXTERNAL 0
#define _BV(bit) (1 << (bit))
#define min(a, b) ((a) < (b)?(a):(b))
#define max(a, b) ((a) > (b)?(a):(b))
#define abs(x) ((x) > 0?(x):-(x))
#define constrain(amt, low, high)
#define round(x) ((x) >= 0 ? (long)((x) + 0.5):(long)((x) - 0.5))
#define radians(deg) ((deg)*DEG_TO_RAD)
#define degrees(rad) ((rad)*RAD_TO_DEG)
#define sq(x) ((x)*(x))
#define interrupts() sei()
#define noInterrupts() cli()
#define clockCyclesPerMicrosecond() (F_CPU / 1000000L)
#define clockCyclesToMicroseconds(a) ((a) / clockCyclesPerMicrosecond())
#define microsecondsToClockCycles(a) ((a) * clockCyclesPerMicrosecond())
#define lowByte(w) ((uint8_t) ((w) & 0xff))
#define highByte(w) ((uint8_t) ((w) >> 8))
#define bitRead(value, bit) (((value) >> (bit)) & 0x01)
#define bitSet(value, bit) ((value) |= (1UL << (bit)))
#define bitClear(value, bit) ((value) &= ~(1UL << (bit)))
#define bitWrite(value, bit, bitvalue)
#define bit(b) (1UL << (b))
#define DEC 10
#define HEX 16
#define OCT 8
#define BIN 2
#define BYTE 0
Typedefs
typedef unsigned int word
typedef uint8_t boolean
typedef uint8_t byte
Functions
void init (void)
void pinMode (uint8_t pin_id, uint8_t mode)
Set the direction of a pin.
void digitalWrite (uint8_t pin_id, uint8_t val)
Write to a pin a given value.
int digitalRead (uint8_t pin_id)
Read a value off a given digital port.
int analogRead (uint8_t pin_id)
void analogReference (uint8_t mode)
void analogWrite (uint8_t pin_id, int val)
unsigned long millis (void)
Returns the number of milli seconds since the Arduino started running.
unsigned long micros (void)
Returns the number of micro seconds since the Arduino started running.
void delay (unsigned long ms)
Delays the program execution for a given amount of milliseconds.
void delayMicroseconds (unsigned int us)
unsigned long pulseIn (uint8_t pin, uint8_t state, unsigned long timeout)
void shiftOut (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder, byte val)
void attachInterrupt (uint8_t pid, void(*fn)(void), int mode)
Attaches an interrupt to a given pin.
void detachInterrupt (uint8_t pid)
Removes an interrupt from a given pin.
void sei ()
Enable interrupts.
void cli ()
Disable interrupts.
void reti ()
Returns from an interrupt routine, enabling global interrupts.
void setup () __attribute__((weak))
Important Must be implemented for the Arduino code to work.
void loop () __attribute__((weak))
Important Must be implemented for the Arduino code to work.
void pinConfiguration ()
Important Must be implemented in the target Arduino Code.
void report ()
Finalizes all of the registered Signal pins.
double run (double length)
Run the emulation for a given amount of time and return the time the simulation ran for.
void initalize_simulator ()
Initialize the simulation.
void reset_simulator ()
Reset the state of the simulation.
bool register_signal (SignalImp *head)
Register a signal used by the simulation.
void processSignal (const char *signal_id)
processSignal represents busy work that a processor will do when dispatching a signal.
void registerPin (const char *signal_id, uint8_t pin_id)
Map a pin to a signal.
void registerSerial (const char *signal_id, const HardwareSerial &serial)
Map a signal to a serial port.
Variables
HardwareSerial Serial
Detailed Description
The main interface to the emulation system.
To interface to the emulator with roughly the same API you would use in normal Arduino code, include this file and link against the static library provided by VEE.
Definition in file arduino.h.
Define Documentation
#define _BV (bit) (1 << (bit))
Definition at line 81 of file arduino.h.
#define abs (x) ((x) > 0?(x):-(x))
Definition at line 90 of file arduino.h.
#define BIN 2
Definition at line 284 of file arduino.h.
#define bit (b) (1UL << (b))
Definition at line 116 of file arduino.h.
#define bitClear (value, bit) ((value) &= ~(1UL << (bit)))
Definition at line 110 of file arduino.h.
#define bitRead (value, bit) (((value) >> (bit)) & 0x01)
Definition at line 108 of file arduino.h.
#define bitSet (value, bit) ((value) |= (1UL << (bit)))
Definition at line 109 of file arduino.h.
#define bitWrite (value, bit, bitvalue)
Value:
(bitvalue ? bitSet(value, bit) \
                                                 : bitClear(value, bit))
Definition at line 111 of file arduino.h.
#define BYTE 0
Definition at line 285 of file arduino.h.
#define CHANGE 1
Definition at line 73 of file arduino.h.
#define clockCyclesPerMicrosecond () (F_CPU / 1000000L)
Definition at line 101 of file arduino.h.
#define clockCyclesToMicroseconds (a) ((a) / clockCyclesPerMicrosecond())
Definition at line 102 of file arduino.h.
#define constrain (amt, low, high)
Value:
((amt) < (low)?(low):((amt) > (high)? \
                                   (high):(amt)))
Definition at line 91 of file arduino.h.
#define DEC 10
Definition at line 281 of file arduino.h.
#define DEFAULT 1
Definition at line 78 of file arduino.h.
#define DEG_TO_RAD 0.017453292519943295769236907684886
Definition at line 64 of file arduino.h.
#define degrees (rad) ((rad)*RAD_TO_DEG)
Definition at line 95 of file arduino.h.
#define DISPLAY 0x1
Definition at line 68 of file arduino.h.
#define EXTERNAL 0
Definition at line 79 of file arduino.h.
#define FALLING 2
Definition at line 74 of file arduino.h.
#define false 0x0
Definition at line 58 of file arduino.h.
#define HALF_PI 1.5707963267948966192313216916398
Definition at line 62 of file arduino.h.
#define HEX 16
Definition at line 282 of file arduino.h.
#define HIGH 0x1
Definition at line 50 of file arduino.h.
#define highByte (w) ((uint8_t) ((w) >> 8))
Definition at line 106 of file arduino.h.
#define INPUT 0x0
Definition at line 53 of file arduino.h.
#define INTERNAL 3
Definition at line 77 of file arduino.h.
#define interrupts () sei()
Definition at line 98 of file arduino.h.
#define LOW 0x0
Definition at line 51 of file arduino.h.
#define lowByte (w) ((uint8_t) ((w) & 0xff))
Definition at line 105 of file arduino.h.
#define LSBFIRST 0
Definition at line 70 of file arduino.h.
#define max (a, b) ((a) > (b)?(a):(b))
Definition at line 89 of file arduino.h.
#define microsecondsToClockCycles (a) ((a) * clockCyclesPerMicrosecond())
Definition at line 103 of file arduino.h.
#define min (a, b) ((a) < (b)?(a):(b))
Definition at line 88 of file arduino.h.
#define MSBFIRST 1
Definition at line 71 of file arduino.h.
#define noInterrupts () cli()
Definition at line 99 of file arduino.h.
#define OCT 8
Definition at line 283 of file arduino.h.
#define OUTPUT 0x1
Definition at line 54 of file arduino.h.
#define PI 3.1415926535897932384626433832795
Definition at line 61 of file arduino.h.
#define RAD_TO_DEG 57.295779513082320876798154814105
Definition at line 65 of file arduino.h.
#define radians (deg) ((deg)*DEG_TO_RAD)
Definition at line 94 of file arduino.h.
#define RISING 3
Definition at line 75 of file arduino.h.
#define round (x) ((x) >= 0 ? (long)((x) + 0.5):(long)((x) - 0.5))
Definition at line 93 of file arduino.h.
#define SERIAL 0x0
Definition at line 67 of file arduino.h.
#define sq (x) ((x)*(x))
Definition at line 96 of file arduino.h.
#define true 0x1
Definition at line 57 of file arduino.h.
#define TWO_PI 6.283185307179586476925286766559
Definition at line 63 of file arduino.h.
Typedef Documentation
typedef uint8_t boolean
Definition at line 118 of file arduino.h.
typedef uint8_t byte
Definition at line 119 of file arduino.h.
typedef unsigned int word
Definition at line 114 of file arduino.h.
Function Documentation
int analogRead (uint8_t pin_id)
Definition at line 30 of file pin_commands.cc.
References ardu, and Ardulator::getPin().
void analogReference (uint8_t mode)
void analogWrite (uint8_t pin_id, int val)
void attachInterrupt (uint8_t pid, void(*)(void) fn, int mode)
Attaches an interrupt to a given pin.
Parameters:
pid The pin number of the interrupt.
fn The callback function for the interrupt
mode The callback conditions.
Definition at line 10 of file interrupt_commands.cc.
References ardu, Ardulator::registerInterrupt(), and sei().
void cli ()
Disable interrupts.
Definition at line 28 of file interrupt_commands.cc.
References ardu, and Ardulator::interrupts_enabled_.
void delay (unsigned long ms)
Delays the program execution for a given amount of milliseconds.
Parameters:
ms Duration of the pause.
Definition at line 12 of file time_commands.cc.
References Ardulator::addTicks(), ardu, and MS2T().
void delayMicroseconds (unsigned int us)
void detachInterrupt (uint8_t pid)
Removes an interrupt from a given pin.
Parameters:
pid The pin number for the interrupt.
Definition at line 16 of file interrupt_commands.cc.
References ardu, and Ardulator::dropInterrupt().
int digitalRead (uint8_t pin_id)
Read a value off a given digital port.
Returns:
Either HIGH or LOW.
Parameters:
pin_id The pin you want to check.
Definition at line 20 of file pin_commands.cc.
References ardu, Ardulator::getPin(), HIGH, and LOW.
void digitalWrite (uint8_t pin_id, uint8_t val)
Write to a pin a given value.
Parameters:
pin_id the pin to write to
val the value to write, should be HIGH or LOW
Definition at line 25 of file pin_commands.cc.
References ardu, and Ardulator::setPin().
void init (void)
void initalize_simulator ()
Initialize the simulation.
Definition at line 36 of file interface.cc.
References initalized, and ardulator::setupArduino().
void loop ()
Important Must be implemented for the Arduino code to work.
This is a standard Arduino function. This function is run multiple times.
unsigned long micros (void)
Returns the number of micro seconds since the Arduino started running.
Returns:
Microseconds
Definition at line 22 of file time_commands.cc.
References ardu, TICKS_PER_SECOND, and Ardulator::timer_.
unsigned long millis (void)
Returns the number of milli seconds since the Arduino started running.
Returns:
Milliseconds
Definition at line 17 of file time_commands.cc.
References ardu, TICKS_PER_SECOND, and Ardulator::timer_.
void pinConfiguration ()
Important Must be implemented in the target Arduino Code.
This function maps the signals of the scenario to specific pins for the duration of the scenario.
See also:
registerPin
registerSerial
void pinMode (uint8_t pin_id, uint8_t mode)
Set the direction of a pin.
Parameters:
pin_id The pin id
mode The direction of the digital pin.
Definition at line 15 of file pin_commands.cc.
References ardu, and Ardulator::configurePin().
void processSignal (const char * signal_id)
processSignal represents busy work that a processor will do when dispatching a signal.
The purpose of this function is to consume CPU cycles since it can be difficult to represent busy work without a much more targeted approach.
Parameters:
signal_id The signal you want to process.
Definition at line 10 of file emulator_commands.cc.
References ardu, and Ardulator::dispatchSignal().
unsigned long pulseIn (uint8_t pin, uint8_t state, unsigned long timeout)
bool register_signal (SignalImp * head)
Register a signal used by the simulation.
Parameters:
head A linked list of signals.
Definition at line 43 of file interface.cc.
References ardu, initalize_simulator(), SignalImp::name, PinConfig::signal_, and Ardulator::unused_pin_config_.
void registerPin (const char * signal_id, uint8_t pin_id)
Map a pin to a signal.
Parameters:
signal_id The signal you want to map
pin_id The pin the signal should be connected to
Definition at line 14 of file emulator_commands.cc.
References Ardulator::addPin(), and ardu.
void registerSerial (const char * signal_id, const HardwareSerial & serial)
Map a signal to a serial port.
This function cheats a bit. It does not check if the hardware actually support Serial communication.
Parameters:
signal_id The signal you want to map
serial The serial port you want to connect to
Definition at line 18 of file emulator_commands.cc.
References Ardulator::addSerial(), and ardu.
void report ()
Finalizes all of the registered Signal pins.
void reset_simulator ()
Reset the state of the simulation.
Definition at line 22 of file interface.cc.
References runtime.
void reti ()
Returns from an interrupt routine, enabling global interrupts.
This should be the last command executed before leaving an ISR.
double run (double length)
Run the emulation for a given amount of time and return the time the simulation ran for.
Parameters:
length How long to run the simulation for.
Definition at line 30 of file interface.cc.
References ardu, initalize_simulator(), and Ardulator::runScenario().
void sei ()
Enable interrupts.
Definition at line 22 of file interrupt_commands.cc.
References ardu, and Ardulator::interrupts_enabled_.
void setup ()
Important Must be implemented for the Arduino code to work.
This is a standard Arduino function. This function is only run once.
void shiftOut (uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder, byte val)
Variable Documentation
HardwareSerial Serial