Virtual Embedded Enviorment: Ardulator Class Reference
Ardulator Class Reference
Main instance of the emulator.
Public Types
typedef std::map< int,
std::pair< int, void(*)(void)> InterruptMap)
typedef InterruptMap::iterator InterruptIterator
typedef std::map< int,
PinConfig * > PinConfigs
typedef PinConfigs::iterator PinConfigIterator
typedef std::map< std::string,
PinConfig * > UnusedPinConfigs
typedef UnusedPinConfigs::iterator UnusedPinConfigIterator
typedef std::map< std::string,
int > SingalNameMap
typedef SingalNameMap::iterator SingalNameMapIterator
Public Member Functions
Ardulator ()
~Ardulator ()
void configurePin (uint8_t id, uint8_t mode)
double runScenario (double length)
Run the scenario for a given length.
void registerInterrupt (uint8_t pin_id, void(*)(void), uint8_t mode)
Registers an interrupt handler.
void dropInterrupt (uint8_t pin_id)
Removes an interrupt handler.
void addPin (std::string signal_name, uint8_t pin_id)
void addSerial (std::string signal_name, const HardwareSerial &serial)
void setPin (uint8_t pin_id, uint8_t val)
int getPin (uint8_t pin_id)
Get the value of a given pin and increment the clock based off the kind of access.
void dispatchSignal (const char *name)
void addTicks (uint64_t)
addTicks is used to increment the interanl clock and increment the total runtime of the emulation.
double now ()
Returns current time as a double instead of the internal time structure format.
void report ()
void log (int level, std::string msg)
void debug (std::string msg="")
void warn (std::string msg="")
void error (std::string msg="")
void info (std::string msg="")
void critical (std::string msg="")
Data Fields
Clock timer_
Current time of the simulation.
InterruptMap interrupts_
A list of interrupts, matching the pin and type to a function callback.
PinConfigs pin_config_
A map of pins to their respective PinConfigs.
UnusedPinConfigs unused_pin_config_
A list of unused pins.
SingalNameMap signal_names_
A map to connect a signal name to a given pin.
FILE * debug_
Debug log file.
std::string * buffers_ [256]
Hardware serial ports buffers.
bool interrupts_enabled_
Controlls the ability to dispatch interrupts.
Private Member Functions
void prepareScenario ()
Initialize the scenario.
void updatePinState ()
Updates pins, checks if we need to fire interrupt.
void updatePinMaps ()
Constructs a mapping of pins to signal names, useful reference.
void finalizePinState ()
Finalize the state of the pins after the scenario is finished.
std::string timestamp ()
Private Attributes
FILE * log_
Log file for all events that happen in the scenario.
double runtime_
The total runtime as a double to make comparisions easier.
std::string registered_identifers_
Clock scenario_length_
The total amount of time the scenario should run.
bool inside_interrupt_handler_
A guard to prevent interrupts from happening inside an interrupt handler.
bool prepared_
A gaurd for initalizing the scenario.
Detailed Description
Main instance of the emulator.
Controls the state of the pins connected. Calls the control code.
See also:
setup
loop
pinConfiguraiton
Definition at line 40 of file ardulator.h.
Member Typedef Documentation
typedef InterruptMap::iterator InterruptIterator
Definition at line 68 of file ardulator.h.
typedef std::map<int, std::pair<int, void (*)(void)> InterruptMap)
Definition at line 67 of file ardulator.h.
typedef PinConfigs::iterator PinConfigIterator
Definition at line 73 of file ardulator.h.
typedef std::map<int, PinConfig*> PinConfigs
Definition at line 72 of file ardulator.h.
typedef std::map<std::string, int> SingalNameMap
Definition at line 80 of file ardulator.h.
typedef SingalNameMap::iterator SingalNameMapIterator
Definition at line 81 of file ardulator.h.
typedef UnusedPinConfigs::iterator UnusedPinConfigIterator
Definition at line 77 of file ardulator.h.
typedef std::map<std::string, PinConfig*> UnusedPinConfigs
Definition at line 76 of file ardulator.h.
Constructor & Destructor Documentation
Ardulator ()
Definition at line 41 of file ardulator.cc.
References Ardulator::debug_, and Ardulator::log_.
~Ardulator ()
Definition at line 58 of file ardulator.cc.
References Ardulator::debug_, and Ardulator::log_.
Member Function Documentation
void addPin (std::string signal_name, uint8_t pin_id)
Definition at line 308 of file ardulator.cc.
References Ardulator::pin_config_, Ardulator::signal_names_, ardulator::thread_lock, and Ardulator::unused_pin_config_.
void addSerial (std::string signal_name, const HardwareSerial & serial)
Definition at line 324 of file ardulator.cc.
References HardwareSerial::pin(), Ardulator::signal_names_, and ardulator::thread_lock.
void addTicks (uint64_t length)
addTicks is used to increment the interanl clock and increment the total runtime of the emulation.
Definition at line 146 of file ardulator.cc.
References Ardulator::runtime_, ardulator::thread_lock, TICKS_PER_SECOND, and Ardulator::timer_.
void configurePin (uint8_t id, uint8_t mode)
Definition at line 69 of file ardulator.cc.
References Ardulator::debug_, and Ardulator::pin_config_.
void critical (std::string msg = "")
void debug (std::string msg = "")
void dispatchSignal (const char * name)
Definition at line 265 of file ardulator.cc.
References Ardulator::addTicks(), Ardulator::debug_, Ardulator::log_, Ardulator::pin_config_, Ardulator::signal_names_, ardulator::thread_lock, TICKS_PER_SECOND, and Ardulator::updatePinState().
void dropInterrupt (uint8_t pin_id)
Removes an interrupt handler.
Parameters:
pin_id the interrupt to remove.
Definition at line 366 of file ardulator.cc.
References Ardulator::interrupts_, Ardulator::pin_config_, and ardulator::thread_lock.
void error (std::string msg = "")
void finalizePinState () [private]
Finalize the state of the pins after the scenario is finished.
For each pin, finalize the state of the pin.
Definition at line 215 of file ardulator.cc.
References Ardulator::pin_config_, and Ardulator::timer_.
int getPin (uint8_t pin_id)
Get the value of a given pin and increment the clock based off the kind of access.
Analog Reads take 100 s Digital Reads 58 cycles
Analog Reads take 100 ms Digital Reads 58 cycles
Definition at line 237 of file ardulator.cc.
References Ardulator::addTicks(), LOW, MS2T(), Ardulator::pin_config_, ardulator::thread_lock, VT_ANALOG, VT_DIGITAL, and VT_SERIAL.
void info (std::string msg = "")
void log (int level, std::string msg)
double now ()
Returns current time as a double instead of the internal time structure format.
Definition at line 227 of file ardulator.cc.
References Ardulator::timer_.
void prepareScenario () [private]
Initialize the scenario.
Prepares the scenario, initializing any variables required for the rest of the simulation.
This is only run once
Definition at line 84 of file ardulator.cc.
References pinConfiguration(), Ardulator::prepared_, setup(), Ardulator::timer_, and Ardulator::updatePinMaps().
void registerInterrupt (uint8_t pin_id, void(*)(void) fn, uint8_t mode)
Registers an interrupt handler.
Parameters:
pin_id interrupt id.
fn function pointer to the interrupt handler.
mode interrupt mode, valid choices, LOW, CHANGE, RISING, FALLING
Definition at line 352 of file ardulator.cc.
References Ardulator::interrupts_, Ardulator::pin_config_, and ardulator::thread_lock.
void report ()
Definition at line 331 of file ardulator.cc.
References Ardulator::pin_config_, and Ardulator::unused_pin_config_.
double runScenario (double length)
Run the scenario for a given length.
Run the scenario for a given amount of time.
Returns:
the exact amount of time the scenario ran for
Definition at line 104 of file ardulator.cc.
References Ardulator::addTicks(), Ardulator::debug_, Ardulator::finalizePinState(), loop(), ardulator::LOOP_CONST, Ardulator::prepareScenario(), Ardulator::runtime_, Ardulator::scenario_length_, TICKS_PER_SECOND, Ardulator::timer_, and Ardulator::updatePinState().
void setPin (uint8_t pin_id, uint8_t val)
Definition at line 257 of file ardulator.cc.
References Ardulator::pin_config_, and ardulator::thread_lock.
string timestamp () [private]
Definition at line 302 of file ardulator.cc.
References Ardulator::timer_.
void updatePinMaps () [private]
Constructs a mapping of pins to signal names, useful reference.
Update the pins so they are connected to the various memory registers.
Definition at line 161 of file ardulator.cc.
References BitValue::getStateRef(), Ardulator::pin_config_, PORTB, PORTC, and PORTD.
void updatePinState () [private]
Updates pins, checks if we need to fire interrupt.
Updates the state of each pin in the internal pin registery.
Definition at line 183 of file ardulator.cc.
References ardulator::ef, Ardulator::inside_interrupt_handler_, Ardulator::pin_config_, Ardulator::scenario_length_, Ardulator::timer_, and Ardulator::unused_pin_config_.
void warn (std::string msg = "")
Field Documentation
std::string* buffers_[256]
Hardware serial ports buffers.
Definition at line 86 of file ardulator.h.
FILE* debug_
Debug log file.
Definition at line 85 of file ardulator.h.
bool inside_interrupt_handler_ [private]
A guard to prevent interrupts from happening inside an interrupt handler.
Definition at line 48 of file ardulator.h.
InterruptMap interrupts_
A list of interrupts, matching the pin and type to a function callback.
Definition at line 69 of file ardulator.h.
bool interrupts_enabled_
Controlls the ability to dispatch interrupts.
Definition at line 88 of file ardulator.h.
FILE* log_ [private]
Log file for all events that happen in the scenario.
Definition at line 42 of file ardulator.h.
PinConfigs pin_config_
A map of pins to their respective PinConfigs.
Definition at line 74 of file ardulator.h.
bool prepared_ [private]
A gaurd for initalizing the scenario.
Definition at line 51 of file ardulator.h.
std::string registered_identifers_ [private]
Definition at line 46 of file ardulator.h.
double runtime_ [private]
The total runtime as a double to make comparisions easier.
Definition at line 44 of file ardulator.h.
Clock scenario_length_ [private]
The total amount of time the scenario should run.
Definition at line 47 of file ardulator.h.
SingalNameMap signal_names_
A map to connect a signal name to a given pin.
Definition at line 82 of file ardulator.h.
Clock timer_
Current time of the simulation.
Definition at line 65 of file ardulator.h.
UnusedPinConfigs unused_pin_config_
A list of unused pins.
Definition at line 78 of file ardulator.h.
The documentation for this class was generated from the following files:
include/ardulator.h
src/ardulator.cc