Virtual Embedded Enviorment: BitValue Class Reference
BitValue Class Reference
A container for a memory register.
#include <bit_value.h>
Public Member Functions
BitValue ()
Construct an empty BitValue memory register.
BitValue (uint8_t state, bool readonly=false)
Construct an empty BitValue memory register.
void updateState (uint8_t val)
Update the memory register to a given value.
uint8_t state () const
Return the current state of the register.
volatile uint8_t * getStateRef ()
Retrieve a reference to the memory register so you can access it from other places.
BitValue & operator= (const BitValue &b)
Assignment overloads, this causes the memory register to act like a signle integer.
BitValue & operator= (const int &b)
Assignment overloads, this causes the memory register to act like a signle integer.
BitValue & operator^= (const BitValue &b)
Bitwise XOR and assignment.
BitValue & operator|= (const BitValue &b)
Bitwise OR and assignment.
BitValue & operator&= (const BitValue &b)
Bitwise AND and assignment.
BitValue & operator^= (const int &b)
Bitwise XOR and assignment.
BitValue & operator|= (const int &b)
Bitwise OR and assignment.
BitValue & operator&= (const int &b)
Bitwise AND and assignment.
BitValue operator~ () const
Bitwise NOT.
BitValue operator^ (const int &b) const
Bitwise XOR.
BitValue operator| (const int &b) const
Bitwise OR.
BitValue operator& (const int &b) const
Bitwise AND.
BitValue operator^ (const BitValue &b) const
Bitwise XOR.
BitValue operator| (const BitValue &b) const
Bitwise OR.
BitValue operator& (const BitValue &b) const
Bitwise AND.
operator int ()
Convert this value into an integer, to make it act like a normal memory register.
Private Attributes
bool ro_
Configuration of the memory register, is it read-only.
volatile uint8_t state_
The state of the memory register, contains each of the bits of the memory register.
Detailed Description
A container for a memory register.
It contains 8 bits and is used to represent special memory locations of the AVR Atmega328p. Currently, used to decribe the DDRx ports and PORTx ports.
Definition at line 17 of file bit_value.h.
Constructor & Destructor Documentation
BitValue ()
Construct an empty BitValue memory register.
Todo:
Add clock ticks
Definition at line 9 of file bit_value.cc.
BitValue (uint8_t state, bool readonly = false)
Construct an empty BitValue memory register.
state Intial state of the memory register. readonly Set the readonly state of the register.
Definition at line 11 of file bit_value.cc.
Member Function Documentation
volatile uint8_t * getStateRef ()
Retrieve a reference to the memory register so you can access it from other places.
See also:
PinConfig::setState
Definition at line 24 of file bit_value.cc.
References BitValue::state_.
operator int ()
Convert this value into an integer, to make it act like a normal memory register.
Definition at line 118 of file bit_value.cc.
References BitValue::state_.
BitValue operator& (const int & b) const
Bitwise AND.
Definition at line 45 of file bit_value.cc.
References BitValue::BitValue(), and BitValue::state_.
BitValue operator& (const BitValue & b) const
Bitwise AND.
Definition at line 114 of file bit_value.cc.
References BitValue::BitValue(), BitValue::state(), and BitValue::state_.
BitValue & operator&= (const BitValue & b)
Bitwise AND and assignment.
Definition at line 85 of file bit_value.cc.
References BitValue::ro_, BitValue::state(), and BitValue::state_.
BitValue & operator&= (const int & b)
Bitwise AND and assignment.
Definition at line 64 of file bit_value.cc.
References BitValue::ro_, and BitValue::state_.
BitValue & operator= (const BitValue & b)
Assignment overloads, this causes the memory register to act like a signle integer.
Definition at line 92 of file bit_value.cc.
References BitValue::ro_, BitValue::state(), and BitValue::state_.
BitValue & operator= (const int & b)
Assignment overloads, this causes the memory register to act like a signle integer.
Definition at line 29 of file bit_value.cc.
References BitValue::state_.
BitValue operator^ (const int & b) const
Bitwise XOR.
Definition at line 35 of file bit_value.cc.
References BitValue::BitValue(), and BitValue::state_.
BitValue operator^ (const BitValue & b) const
Bitwise XOR.
Definition at line 104 of file bit_value.cc.
References BitValue::BitValue(), BitValue::state(), and BitValue::state_.
BitValue & operator^= (const BitValue & b)
Bitwise XOR and assignment.
Definition at line 71 of file bit_value.cc.
References BitValue::ro_, BitValue::state(), and BitValue::state_.
BitValue & operator^= (const int & b)
Bitwise XOR and assignment.
Definition at line 50 of file bit_value.cc.
References BitValue::ro_, and BitValue::state_.
BitValue operator| (const int & b) const
Bitwise OR.
Definition at line 40 of file bit_value.cc.
References BitValue::BitValue(), and BitValue::state_.
BitValue operator| (const BitValue & b) const
Bitwise OR.
Definition at line 109 of file bit_value.cc.
References BitValue::BitValue(), BitValue::state(), and BitValue::state_.
BitValue & operator|= (const BitValue & b)
Bitwise OR and assignment.
Definition at line 78 of file bit_value.cc.
References BitValue::ro_, BitValue::state(), and BitValue::state_.
BitValue & operator|= (const int & b)
Bitwise OR and assignment.
Definition at line 57 of file bit_value.cc.
References BitValue::ro_, and BitValue::state_.
BitValue operator~ () const
Bitwise NOT.
Definition at line 99 of file bit_value.cc.
References BitValue::BitValue(), and BitValue::state_.
uint8_t state () const
Return the current state of the register.
Definition at line 20 of file bit_value.cc.
References BitValue::state_.
void updateState (uint8_t val)
Update the memory register to a given value.
val the new value for the state of this register.
Definition at line 15 of file bit_value.cc.
References BitValue::state_.
Field Documentation
bool ro_ [private]
Configuration of the memory register, is it read-only.
Definition at line 18 of file bit_value.h.
volatile uint8_t state_ [private]
The state of the memory register, contains each of the bits of the memory register.
Definition at line 19 of file bit_value.h.
The documentation for this class was generated from the following files:
include/ardulator/containers/bit_value.h
src/ardulator/containers/bit_value.cc