Virtual Embedded Enviorment: MainWindow Class Reference
MainWindow Class Reference
Main application window.
Public Member Functions
def __init__
def connectComponents
def addSignal
def getCurrentSignalId
def runScenario
def updatePinConfiguration
def resetData
def browse
def openScenario
def saveScenario
def onOutputPinsListSelect
Data Fields
ui
settings
Static Public Attributes
tuple list_changed = QtCore.Signal()
Private Member Functions
def _saveAs
Detailed Description
Main application window.
Definition at line 62 of file vee-gui.py.
Constructor & Destructor Documentation
def __init__ (self, ui)
Definition at line 65 of file vee-gui.py.
Member Function Documentation
def _saveAs (self, filename) [private]
Definition at line 269 of file vee-gui.py.
References MainWindow::settings.
def addSignal (self)
Add a signal to the list of signals.
Definition at line 135 of file vee-gui.py.
def browse (self)
Definition at line 226 of file vee-gui.py.
References MainWindow::ui.
def connectComponents (self)
Definition at line 74 of file vee-gui.py.
References MainWindow::addSignal(), MainWindow::browse(), MainWindow::onOutputPinsListSelect(), MainWindow::openScenario(), MainWindow::resetData(), Ardulator::runScenario(), MainWindow::runScenario(), MainWindow::saveScenario(), MainWindow::ui, and MainWindow::updatePinConfiguration().
def getCurrentSignalId (self)
Get the name of the current Signal
Definition at line 144 of file vee-gui.py.
def onOutputPinsListSelect (self, value, previous_value)
Definition at line 274 of file vee-gui.py.
References MainWindow::settings.
def openScenario (self)
Open a given scenario's configuration.
Definition at line 241 of file vee-gui.py.
References MainWindow::settings.
def resetData (self)
Definition at line 222 of file vee-gui.py.
References MainWindow::settings.
def runScenario (self)
Definition at line 152 of file vee-gui.py.
References MainWindow::_saveAs().
def saveScenario (self)
Definition at line 254 of file vee-gui.py.
References MainWindow::_saveAs(), and MainWindow::settings.
def updatePinConfiguration (self)
Definition at line 164 of file vee-gui.py.
References MainWindow::getCurrentSignalId(), and MainWindow::settings.
Field Documentation
tuple list_changed = QtCore.Signal() [static]
Definition at line 63 of file vee-gui.py.
settings
Definition at line 65 of file vee-gui.py.
ui
Definition at line 65 of file vee-gui.py.
The documentation for this class was generated from the following file:
src/vee-gui.py