Virtual Embedded Enviorment: Print Class Reference
Print Class Reference
Printing utilities, requires the implementation of the Print::write function to work.
Public Member Functions
virtual void write (uint8_t)=0
virtual void write (const char *str)
virtual void write (const uint8_t *buffer, size_t size)
void print (const char[])
void print (const std::string &s)
void print (char, int=BYTE)
void print (unsigned char, int=BYTE)
void print (int, int=DEC)
void print (unsigned int, int=DEC)
void print (long, int=DEC)
void print (unsigned long, int=DEC)
void print (double, int=2)
void println (const char[])
void println (const std::string &s)
void println (char, int=BYTE)
void println (unsigned char, int=BYTE)
void println (int, int=DEC)
void println (unsigned int, int=DEC)
void println (long, int=DEC)
void println (unsigned long, int=DEC)
void println (double, int=2)
void println (void)
Private Member Functions
void printNumber (unsigned long, uint8_t)
void printFloat (double, uint8_t)
Detailed Description
Printing utilities, requires the implementation of the Print::write function to work.
Definition at line 291 of file arduino.h.
Member Function Documentation
void print (const char str[])
Definition at line 86 of file hardware_serial.cc.
References write().
void print (const std::string & s)
Definition at line 80 of file hardware_serial.cc.
References write().
void print (char c, int base = BYTE)
Definition at line 90 of file hardware_serial.cc.
References print().
void print (unsigned char b, int base = BYTE)
Definition at line 94 of file hardware_serial.cc.
References print().
void print (int n, int base = DEC)
Definition at line 98 of file hardware_serial.cc.
References print().
void print (unsigned int n, int base = DEC)
Definition at line 102 of file hardware_serial.cc.
References print().
void print (long n, int base = DEC)
Definition at line 106 of file hardware_serial.cc.
References print(), printNumber(), and write().
void print (unsigned long n, int base = DEC)
Definition at line 120 of file hardware_serial.cc.
References printNumber(), and write().
void print (double n, int digits = 2)
Definition at line 125 of file hardware_serial.cc.
References printFloat().
void printFloat (double number, uint8_t digits) [private]
Definition at line 34 of file hardware_serial.cc.
References print().
void println (const char c[])
Definition at line 139 of file hardware_serial.cc.
References print(), and println().
void println (const std::string & s)
Definition at line 134 of file hardware_serial.cc.
References print(), and println().
void println (char c, int base = BYTE)
Definition at line 144 of file hardware_serial.cc.
References print(), and println().
void println (unsigned char b, int base = BYTE)
Definition at line 149 of file hardware_serial.cc.
References print(), and println().
void println (int n, int base = DEC)
Definition at line 154 of file hardware_serial.cc.
References print(), and println().
void println (unsigned int n, int base = DEC)
Definition at line 159 of file hardware_serial.cc.
References print(), and println().
void println (long n, int base = DEC)
Definition at line 164 of file hardware_serial.cc.
References print(), and println().
void println (unsigned long n, int base = DEC)
Definition at line 169 of file hardware_serial.cc.
References print(), and println().
void println (double n, int digits = 2)
Definition at line 174 of file hardware_serial.cc.
References print(), and println().
void println (void)
Definition at line 129 of file hardware_serial.cc.
References print().
void printNumber (unsigned long n, uint8_t base) [private]
Definition at line 14 of file hardware_serial.cc.
References print().
virtual void write (uint8_t) [pure virtual]
Implemented in HardwareSerial.
void write (const char * str) [virtual]
Definition at line 69 of file hardware_serial.cc.
References write().
void write (const uint8_t * buffer, size_t size) [virtual]
Definition at line 75 of file hardware_serial.cc.
References write().
The documentation for this class was generated from the following files:
include/arduino.h
src/ardulator/hardware_serial.cc