Virtual Embedded Enviorment: src/emulator_commands.cc File Reference
src/emulator_commands.cc File Reference
#include <string>
#include "ardulator.h"
#include "arduino.h"
Functions
void processSignal (const char *signal_id)
processSignal represents busy work that a processor will do when dispatching a signal.
void registerPin (const char *signal_id, uint8_t pin_id)
Map a pin to a signal.
void registerSerial (const char *signal_id, const HardwareSerial &serial)
Map a signal to a serial port.
Function Documentation
void processSignal (const char * signal_id)
processSignal represents busy work that a processor will do when dispatching a signal.
The purpose of this function is to consume CPU cycles since it can be difficult to represent busy work without a much more targeted approach.
Parameters:
signal_id The signal you want to process.
Definition at line 10 of file emulator_commands.cc.
References ardu, and Ardulator::dispatchSignal().
void registerPin (const char * signal_id, uint8_t pin_id)
Map a pin to a signal.
Parameters:
signal_id The signal you want to map
pin_id The pin the signal should be connected to
Definition at line 14 of file emulator_commands.cc.
References Ardulator::addPin(), and ardu.
void registerSerial (const char * signal_id, const HardwareSerial & serial)
Map a signal to a serial port.
This function cheats a bit. It does not check if the hardware actually support Serial communication.
Parameters:
signal_id The signal you want to map
serial The serial port you want to connect to
Definition at line 18 of file emulator_commands.cc.
References Ardulator::addSerial(), and ardu.