Virtual Embedded Enviorment: src/c_interface/interface.cc File Reference
src/c_interface/interface.cc File Reference
#include "arduino.h"
#include "ardulator.h"
Functions
void reset_simulator ()
Reset the state of the simulation.
void step ()
double run (double length)
Run the emulation for a given amount of time and return the time the simulation ran for.
void initalize_simulator ()
Initialize the simulation.
bool register_signal (SignalImp *first)
Register a signal used by the simulation.
Variables
static double runtime = 0
static bool initalized = false
Function Documentation
void initalize_simulator ()
Initialize the simulation.
Definition at line 36 of file interface.cc.
References initalized, and ardulator::setupArduino().
bool register_signal (SignalImp * head)
Register a signal used by the simulation.
Parameters:
head A linked list of signals.
Definition at line 43 of file interface.cc.
References ardu, initalize_simulator(), SignalImp::name, PinConfig::signal_, and Ardulator::unused_pin_config_.
void reset_simulator ()
Reset the state of the simulation.
Definition at line 22 of file interface.cc.
References runtime.
double run (double length)
Run the emulation for a given amount of time and return the time the simulation ran for.
Parameters:
length How long to run the simulation for.
Definition at line 30 of file interface.cc.
References ardu, initalize_simulator(), and Ardulator::runScenario().
void step ()
Todo:
Implement step. To step through an execution of the emulation.
Definition at line 26 of file interface.cc.
Variable Documentation
bool initalized = false [static]
Definition at line 20 of file interface.cc.
double runtime = 0 [static]
Definition at line 19 of file interface.cc.