Virtual Embedded Enviorment: src/interrupt_commands.cc File Reference
src/interrupt_commands.cc File Reference
Functions
void attachInterrupt (uint8_t pin_id, void(*fn)(void), int mode)
Attaches an interrupt to a given pin.
void detachInterrupt (uint8_t pin_id)
Removes an interrupt from a given pin.
void sei ()
Enable interrupts.
void cli ()
Disable interrupts.
Function Documentation
void attachInterrupt (uint8_t pid, void(*)(void) fn, int mode)
Attaches an interrupt to a given pin.
Parameters:
pid The pin number of the interrupt.
fn The callback function for the interrupt
mode The callback conditions.
Definition at line 10 of file interrupt_commands.cc.
References ardu, Ardulator::registerInterrupt(), and sei().
void cli ()
Disable interrupts.
Definition at line 28 of file interrupt_commands.cc.
References ardu, and Ardulator::interrupts_enabled_.
void detachInterrupt (uint8_t pid)
Removes an interrupt from a given pin.
Parameters:
pid The pin number for the interrupt.
Definition at line 16 of file interrupt_commands.cc.
References ardu, and Ardulator::dropInterrupt().
void sei ()
Enable interrupts.
Definition at line 22 of file interrupt_commands.cc.
References ardu, and Ardulator::interrupts_enabled_.