"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/vee-gui.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'optimize': 2,
    'compressed' : True,
    'iconfile' : './resources/processing.icns',
    'strip': False,
    # 'frameworks': ['/usr/local/lib/QtCore.framework', '/usr/local/lib/QtGui.framework']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
